### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lauraperezcerrato** [pythonic-emacs/company-anaconda#29]
Hi! I'm currently using Emacs 25.3.1 on the terminal on top of Fedora 28 (The version that Emacs reports is `GNU Emacs 25.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.26) of 2018-01-12`)

When installing `company-anaconda` from MELPA (version `20180429.1712`) I get the following error:

`company-anaconda.el:86:1:Error: Symbol’s value as variable is void: rx-constituents`

Reverting the code to that before this commit https://github.com/proofit404/company-anaconda/commit/f46960ec6aea72496fbb9966a3c126ca989cfd8a "solves" the issue.

**Comment by aiace9** [comment]
Same problem here. Fedora 26, Emacs 25.3.1, gtk 3.22.19
The error is in the same line, I didn't try to revert the code yet.

**Comment by muffinmad** [comment]
Try to ```(require 'rx)```

**Comment by dsana123** [comment]
Adding `(require 'rx)` fixed the problem for me, I can now install `company-anaconda` from MELPA.

**Comment by aiace9** [comment]
I can confirm, problem solved

**Comment by falloutphil** [comment]
It still seems necessary to manually add `(require 'rx)` to emacs config - should this be kept open until someone gets a chance to add the dependency to the package itself?

**Comment by CeleritasCelery** [comment]
Thanks @falloutphil, that is the correct solution.
